### ISSUE TITLE
consumer gets error

### ISSUE THREAD

**Issue by psyntium** [ibm-messaging/message-hub-rest#6]
`consumerInstance.get(topicName)` is giving me the following error:

```
{
     "error_code" : 40601,
     "message" : "The requested embedded data format does not match the deserializer for this consumer instance"
 }

```

**Comment by mimaison** [comment]
This has been answered on StackOverflow: https://stackoverflow.com/questions/49792926/message-hub-rest-api-consumer-error

Closing
