### ISSUE TITLE
Consumers broken by change to admin URL from rest URL

### ISSUE THREAD

**Issue by mattbaileyuk** [ibm-messaging/message-hub-rest#8]
The change in https://github.com/ibm-messaging/message-hub-rest/pull/7 was a breaking change for consumers of this library as they now need to pass through a different parameter. It wasn't clear in the PR why this change was being made; if it was intentional to make a breaking change then the major version should be bumped so consumers can stay on `1.x` and adopt `2.x` with the changes when ready.

**Comment by nweedo3** [comment]
@mattbaileyuk thanks for picking this up - I'll revert the change and bump it to `2.0.0` instead.

**Comment by nweedo3** [comment]
@mattbaileyuk thanks for the heads-up, version `1.3.0` has been republished at `2.0.0-alpha.0`.
